version: "2"
plugins:
  checkstyle:
    enabled: true
checks:
  method-lines:
    config:
      threshold: 80 # No more than 2 screens
  method-complexity:
    config:
      threshold: 15 # We are Russian hackers!
  similar-code:
    config:
      threshold: 60 # Sometimes it is not so similar
  identical-code:
    config:
      threshold: 60 # Nope, not a duplicate
